

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "Fab.City" # the name of your site, e.g. ACME Corp.
tagline: "LOCALLY PRODUCED, GLOBALLY CONNECTED"
email: "your.email@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
author: Joris Vos
url: "Fab.City" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username:
  card: summary #keep this to generate a twitter share card
